### ISSUE TITLE
Add wlanpi-mode command

### ISSUE THREAD

**Issue by jiribrejcha** [WLAN-Pi/wlanpi-common#15]
One thing that becomes apparent very quickly when using a headless WLAN Pi is the difficulty switching modes, as all the cli commands for he various modes are different. I suggest a new common cli command as follows. 

Usage:

wlanpi-mode          - returns current mode
wlanpi-mode classic  - switch from current mode back to classic
wlanpi-mode wconsole - switch to wconsole mode
wlanpi-mode hotspot  - switch to hotspot mode
wlanpi-mode server   - switch to server mode

Thanks to Nigel for the idea and suggestion.

**Comment by adriangranados** [comment]
If we follow the convention for other commands, it should be `wlanpi-mode get` to show current mode, and `wlanpi-mode set <mode>` to switch to a different mode.

**Comment by jiribrejcha** [comment]
I believe @wifinigel has already done this.

**Comment by wifinigel** [comment]
Yes, completed.
