### ISSUE TITLE
Detect WLAN Pi model and apply the right system config

### ISSUE THREAD

**Issue by jiribrejcha** [WLAN-Pi/wlanpi-common#26]
Namely Pro, RPi4 CE, MCUzone CE.

Settings:
- USB port mode
- Fan controller
- Enable display out of the box

**Comment by joshschmelzle** [comment]
Closing as this appears to be solved in https://github.com/WLAN-Pi/wlanpi-common/blob/main/opt/wlanpi-common/wlanpi-config-at-startup.sh
