### ISSUE TITLE
wlanpi-reg-domain command is broken

### ISSUE THREAD

**Issue by jiribrejcha** [WLAN-Pi/wlanpi-common#27]
Reported by Adrian:

I did notice that the wlanpi-reg-domain command is broken:

wlanpi@wlanpi-275:~ $ sudo wlanpi-reg-domain get
Error extracting reg domain from /etc/default/crda
wlanpi@wlanpi-275:~ $ sudo iw reg get
global
country 00: DFS-UNSET
	(755 - 928 @ 2), (N/A, 20), (N/A), NO-IR
	(2402 - 2472 @ 40), (N/A, 20), (N/A)
	(2457 - 2482 @ 20), (N/A, 20), (N/A), AUTO-BW, NO-IR
	(2474 - 2494 @ 20), (N/A, 20), (N/A), NO-OFDM, NO-IR
	(5170 - 5250 @ 80), (N/A, 20), (N/A), AUTO-BW, NO-IR
	(5250 - 5330 @ 80), (N/A, 20), (0 ms), DFS, AUTO-BW, NO-IR
	(5490 - 5730 @ 160), (N/A, 20), (0 ms), DFS, NO-IR
	(5735 - 5835 @ 80), (N/A, 20), (N/A), NO-IR
	(57240 - 63720 @ 2160), (N/A, 0), (N/A)

wlanpi@wlanpi-275:~ $ sudo iw reg set US
wlanpi@wlanpi-275:~ $ sudo iw reg get
global
country US: DFS-FCC
	(902 - 904 @ 2), (N/A, 30), (N/A)
	(904 - 920 @ 16), (N/A, 30), (N/A)
	(920 - 928 @ 8), (N/A, 30), (N/A)
	(2400 - 2472 @ 40), (N/A, 30), (N/A)
	(5150 - 5250 @ 80), (N/A, 23), (N/A), AUTO-BW
	(5250 - 5350 @ 80), (N/A, 24), (0 ms), DFS, AUTO-BW
	(5470 - 5730 @ 160), (N/A, 24), (0 ms), DFS
	(5730 - 5850 @ 80), (N/A, 30), (N/A), AUTO-BW
	(5850 - 5895 @ 40), (N/A, 27), (N/A), NO-OUTDOOR, AUTO-BW, NO-IR
	(57240 - 71000 @ 2160), (N/A, 40), (N/A)

wlanpi@wlanpi-275:~ $ sudo wlanpi-reg-domain get
Error extracting reg domain from /etc/default/crda

**Comment by joshschmelzle** [comment]
This is not reproducible in v3.1.0 image. I'm not sure which version of wlanpi-common fixes this issue, but am closing.
