### ISSUE TITLE
lldpcleanup does not run when lldpneigh.sh is run from /usr/bin

### ISSUE THREAD

**Issue by joshschmelzle** [WLAN-Pi/wlanpi-common#6]
The following line [#20 in lldpneigh.sh](
https://github.com/WLAN-Pi/wlanpi-common/blob/main/opt/wlanpi-common/networkinfo/lldpneigh.sh#L20) does not follow the symlink when run from /usr/bin:

```
DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
```

Output includes:

```
sudo: /usr/bin/lldpcleanup.sh: command not found
```

Soft link:

```
 ls -la /usr/bin | grep lldp
lrwxrwxrwx  1 root root            43 Dec 12 12:19 lldpneigh -> /opt/wlanpi-common/networkinfo/lldpneigh.sh
```

Possible solution is to add lldpcleanup.sh link to /usr/bin

**Comment by jiribrejcha** [comment]
Fixed in https://github.com/WLAN-Pi/wlanpi-common/commit/36e0fcc888ae84bb2a29e72a5e6c0fd416fc002e

Thank you @joshschmelzle.
